sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script:
  - if [ -n "${TRAVIS_TAG}" ]; then
       deploy/deploy.sh;
    fi
  - docker images



